### ISSUE TITLE
Rewaita not opening on Arch Linux

### ISSUE THREAD

**Issue by chrrybmb64** [SwordPuffin/Rewaita#48]
I installed Rewaita 1.0.8 today from the AUR and unfortunately it won't open. Here is the error the command line gives me:

```
rewaita
Traceback (most recent call last):
  File "/usr/bin/rewaita", line 46, in <module>
    from rewaita import main
  File "/usr/share/rewaita/rewaita/main.py", line 27, in <module>
    from .window import RewaitaWindow
  File "/usr/share/rewaita/rewaita/window.py", line 24, in <module>
    from .custom_theme_page import CustomPage
  File "/usr/share/rewaita/rewaita/custom_theme_page.py", line 3, in <module>
    gi.require_version('GtkSource', '5')
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/gi/__init__.py", line 132, in require_version
    raise ValueError('Namespace %s not available for version %s' %
                     (namespace, version))
ValueError: Namespace GtkSource not available for version 5

**Comment by TAforever** [comment]
Also, when building the package, I get these errors, and if the application window does appear sometimes, it has no content. By the way, I tried the flatpak version and got the same result: the application doesn't work (Arch Linux)

```
bsdtar: usr/share/rewaita/rewaita/dark/Catppuccin Frappe 🪴.css: Can't translate pathname 'usr/share/rewaita/rewaita/dark/Catppuccin Frappe 🪴.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/dark/Catppuccin Mocha 🌿.css: Can't translate pathname 'usr/share/rewaita/rewaita/dark/Catppuccin Mocha 🌿.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/dark/Dracula 🧛🏻‍♂️.css: Can't translate pathname 'usr/share/rewaita/rewaita/dark/Dracula 🧛🏻‍♂️.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/dark/Everforest 🌲.css: Can't translate pathname 'usr/share/rewaita/rewaita/dark/Everforest 🌲.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/dark/Gruvbox Medium 🌴.css: Can't translate pathname 'usr/share/rewaita/rewaita/dark/Gruvbox Medium 🌴.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/dark/Gruvbox Soft 🌱.css: Can't translate pathname 'usr/share/rewaita/rewaita/dark/Gruvbox Soft 🌱.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/dark/Kanagawa 🌊.css: Can't translate pathname 'usr/share/rewaita/rewaita/dark/Kanagawa 🌊.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/dark/Material Deepocean 🐚.css: Can't translate pathname 'usr/share/rewaita/rewaita/dark/Material Deepocean 🐚.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/dark/Material Palenight 🌙.css: Can't translate pathname 'usr/share/rewaita/rewaita/dark/Material Palenight 🌙.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/dark/Nightfox 🦊.css: Can't translate pathname 'usr/share/rewaita/rewaita/dark/Nightfox 🦊.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/dark/Nord 🏔️.css: Can't translate pathname 'usr/share/rewaita/rewaita/dark/Nord 🏔️.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/dark/One Dark ⚛️.css: Can't translate pathname 'usr/share/rewaita/rewaita/dark/One Dark ⚛️.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/dark/Rosé Pine Moon 🌒.css: Can't translate pathname 'usr/share/rewaita/rewaita/dark/Rosé Pine Moon 🌒.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/dark/Rosé Pine 🌹.css: Can't translate pathname 'usr/share/rewaita/rewaita/dark/Rosé Pine 🌹.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/dark/Solarized ☀️.css: Can't translate pathname 'usr/share/rewaita/rewaita/dark/Solarized ☀️.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/dark/Synthwave '84 🌅.css: Can't translate pathname 'usr/share/rewaita/rewaita/dark/Synthwave '84 🌅.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/dark/Tokyonight Storm 🌪️.css: Can't translate pathname 'usr/share/rewaita/rewaita/dark/Tokyonight Storm 🌪️.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/dark/Tokyonight 🗼.css: Can't translate pathname 'usr/share/rewaita/rewaita/dark/Tokyonight 🗼.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/light/Alucard 🧛🏻‍♂️.css: Can't translate pathname 'usr/share/rewaita/rewaita/light/Alucard 🧛🏻‍♂️.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/light/Catppuccin Latte 🌻.css: Can't translate pathname 'usr/share/rewaita/rewaita/light/Catppuccin Latte 🌻.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/light/Dawnfox 🦊.css: Can't translate pathname 'usr/share/rewaita/rewaita/light/Dawnfox 🦊.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/light/Everforest 🌲.css: Can't translate pathname 'usr/share/rewaita/rewaita/light/Everforest 🌲.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/light/Gruvbox Medium 🌴.css: Can't translate pathname 'usr/share/rewaita/rewaita/light/Gruvbox Medium 🌴.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/light/Gruvbox Soft 🌱.css: Can't translate pathname 'usr/share/rewaita/rewaita/light/Gruvbox Soft 🌱.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/light/Kanagawa 🌊.css: Can't translate pathname 'usr/share/rewaita/rewaita/light/Kanagawa 🌊.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/light/Nord 🏔️.css: Can't translate pathname 'usr/share/rewaita/rewaita/light/Nord 🏔️.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/light/Rosé Pine Dawn 🌄.css: Can't translate pathname 'usr/share/rewaita/rewaita/light/Rosé Pine Dawn 🌄.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/light/Solarized ☀️.css: Can't translate pathname 'usr/share/rewaita/rewaita/light/Solarized ☀️.css' to UTF-8
bsdtar: usr/share/rewaita/rewaita/light/Tokyonight 🗼.css: Can't translate pathname 'usr/share/rewaita/rewaita/light/Tokyonight 🗼.css' to UTF-8
```

<img width="867" height="748" alt="Image" src="https://github.com/user-attachments/assets/6f05f509-acf8-4209-be07-b23422ebc2da" />

**Comment by SwordPuffin** [comment]
I'm fairly certain this is because the AUR version doesn't install GtkSource as a dependency.

The problem is that version is packaged by a third-party maintainer with whom I have no connection or contact with.

I will ping them here and hope they fix it immediately.

Thanks,
NP.

**Comment by SwordPuffin** [comment]
@yochananmarqos

**Comment by SwordPuffin** [comment]
@TAforever 

Try deleting both the AUR and Flatpak versions, then removing ~/.var/app/io.github.swordpuffin.rewaita/data/prefs.json.

And then re-install the Flatpak version.

That should fix the issue.

**Comment by TAforever** [comment]
> [@TAforever](https://github.com/TAforever)
> 
> Try deleting both the AUR and Flatpak versions, then removing ~/.var/app/io.github.swordpuffin.rewaita/data/prefs.json.
> 
> And then re-install the Flatpak version.
> 
> That should fix the issue.

I did as you said, but everything is still the same. Here is the terminal output:
```Traceback (most recent call last):
  File "/app/share/rewaita/rewaita/main.py", line 157, in do_command_line
    win = RewaitaWindow(application=self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/rewaita/rewaita/window.py", line 94, in __init__
    self.pref = self.settings.read_uint("org.freedesktop.appearance", "color-scheme")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^```

**Comment by TAforever** [comment]
If I run it again in a second terminal, the window appears but it is empty (flatpak)

<img width="795" height="936" alt="Image" src="https://github.com/user-attachments/assets/3f0a29fa-7327-48d3-9ded-e64705786b85" />

**Comment by SwordPuffin** [comment]
I'm curious if it's because you are running a window manager. Because that schema that it's trying to read is for light/dark mode.

But most likely, that isn't the issue.

**Comment by TAforever** [comment]
> I'm curious if it's because you are running a window manager. Because that schema that it's trying to read is for light/dark mode.
> 
> But most likely, that isn't the issue.

I use dwl

**Comment by SwordPuffin** [comment]
When the window launches, does it read your light/dark mode configuration correctly?

I'm just wondering because on Gnome or Cinnamon, those settings are very transparent for developers, but on DWM, they may be more opaque.

**Comment by SwordPuffin** [comment]
Just FYI, I'm not going to ask you to download Gnome or anything.

Hopefully, we can fix this rn.

**Comment by SwordPuffin** [comment]
> I installed Rewaita 1.0.8 today from the AUR and unfortunately it won't open. Here is the error the command line gives me:
> 
> ```
> rewaita
> Traceback (most recent call last):
>   File "/usr/bin/rewaita", line 46, in <module>
>     from rewaita import main
>   File "/usr/share/rewaita/rewaita/main.py", line 27, in <module>
>     from .window import RewaitaWindow
>   File "/usr/share/rewaita/rewaita/window.py", line 24, in <module>
>     from .custom_theme_page import CustomPage
>   File "/usr/share/rewaita/rewaita/custom_theme_page.py", line 3, in <module>
>     gi.require_version('GtkSource', '5')
>     ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.13/site-packages/gi/__init__.py", line 132, in require_version
>     raise ValueError('Namespace %s not available for version %s' %
>                      (namespace, version))
> ValueError: Namespace GtkSource not available for version 5

I think the AUR maintainer just added GtkSource as a dependency, so if you do a clean install it might work.

**Comment by chrrybmb64** [comment]
I can confirm that Rewaita now opens with the added dependency, thanks.

I got the same errors during the build process as TAforever, but the build completed and as far as I can tell they haven't affected anything.

**Comment by psypherium** [comment]
Tested with the second packaging of Rewaita main from AUR: 1.0.8-2.

I can confirm that Rewaita still refuses to open when only the dependencies in the arch pkgbuild are installed. Tested right now on a live manjaro usb, this test method ensures that dependencies have not been pulled by another installed app.

Rewaita is still only able to start when run from terminal on both cachyOS persistent and Manjaro-GNOME live.

After the Rewaita background process is launched, Rewaita can then be opened via the icon.

If the Rewaita background process is closed, Rewaita can no longer be opened with the icon.

I am seeing the blank Rewaita window when it is launched from terminal on a live install.

On a persistent install the window was not blank. (This Rewaita was originally installed before the issue began.)

Was gtksourceview5 the dependency which was just added? Because it seems to be not enough.

**Comment by psypherium** [comment]
This issue is not exactly a duplicate of #40 but probably both issues can be closed when this is resolved.

**Comment by TAforever** [comment]
I figured out what the problem was: I needed to have `xdg-desktop-portal-gtk` installed, but I only had `xdg-desktop-portal-wlr`. Now everything works

**Comment by psypherium** [comment]
> I figured out what the problem was: I needed to have `xdg-desktop-portal-gtk` installed, but I only had `xdg-desktop-portal-wlr`. Now everything works

I've commented on the Rewaita AUR package page about the xdg-desktop-portal-gtk dependency requirement.

There is still something missing for me, I am getting the same blank Rewaita the same as the images posted in this thread.

**Comment by TAforever** [comment]
> > I figured out what the problem was: I needed to have `xdg-desktop-portal-gtk` installed, but I only had `xdg-desktop-portal-wlr`. Now everything works
> 
> I've commented on the Rewaita AUR package page about the xdg-desktop-portal-gtk dependency requirement.
> 
> There is still something missing for me, I am getting the same blank Rewaita the same as the images posted in this thread.

Strange, it should work after a reboot. It's just that the wlr portal is quite basic and doesn't have the necessary interface, while other portals do https://wiki.archlinux.org/title/XDG_Desktop_Portal#List_of_backends_and_interfaces

**Comment by SwordPuffin** [comment]
Hmmm...

The issue with xdg-desktop-portal-gtk is that I don't think it supports running in the background which is important.

I think the Flatpak runs with xdg-desktop-portal-gnome as that is default for GTK4 and Libadwaita. Installing that might knock some sense into your machine.

**Comment by SwordPuffin** [comment]
The reason why the application window would launch but still be empty is because something is breaking between when the app starts, and when it finishes building the interface.

It's probably [this](https://github.com/SwordPuffin/Rewaita/blob/31b1f81969d8fd3bd392d335b88f92f90dc380d9/src/window.py#L131C1-L131C90) because some portals like the wlr and hyprland don't have access to settings.

**Comment by psypherium** [comment]
> The issue with xdg-desktop-portal-gtk is that I don't think it supports running in the background which is important.
>  (Truncated)

The issue with xdg-desktop-portal-gtk is that I don't think it supports running _other applications_ in the background, which is important. (xdg-desktop-portal-gnome is required to launch the Rewaita background process, and to maintain it after Rewaita is closed(?))

FTFY sorry, I couldn't think correctly after reading that. Is the bracketed part correct?

Perhaps the Rewaita background process could instead be a systemd service unit, this could alleviate reliance on xdg-desktop-portal-gnome?
